(
  define
  (problem instance-5)
  (:domain satellite)
  (:objects instrument11 instrument1 star7 instrument10 star13 planet20 infrared3 phenomenon19 instrument4 instrument2 star18 instrument7 infrared0 groundstation4 star5 phenomenon21 groundstation8 instrument8 star15 satellite3 instrument0 image2 instrument5 satellite1 star11 instrument9 groundstation0 groundstation6 satellite0 satellite2 star3 groundstation10 phenomenon17 groundstation1 phenomenon12 planet14 groundstation9 star16 groundstation2 image1 instrument3 instrument6)
  (
    :init
    (direction__________ groundstation10)
    (supports instrument11 infrared0)
    (calibration_target instrument2 groundstation4)
    (on_board instrument9 satellite3)
    (supports instrument2 image1)
    (supports instrument3 infrared3)
    (on_board instrument3 satellite1)
    (pointing satellite2 star5)
    (instrument_________ instrument0)
    (direction__________ star11)
    (satellite__________ satellite1)
    (mode_______________ image1)
    (instrument_________ instrument1)
    (supports instrument4 image2)
    (calibration_target instrument7 groundstation1)
    (pointing satellite3 planet20)
    (instrument_________ instrument10)
    (direction__________ phenomenon19)
    (direction__________ groundstation1)
    (direction__________ groundstation9)
    (on_board instrument2 satellite0)
    (calibration_target instrument2 groundstation1)
    (on_board instrument5 satellite1)
    (supports instrument5 image2)
    (on_board instrument11 satellite3)
    (calibration_target instrument11 star3)
    (supports instrument10 image2)
    (supports instrument5 infrared0)
    (direction__________ star16)
    (power_avail satellite0)
    (power_avail satellite2)
    (pointing satellite1 groundstation8)
    (calibration_target instrument3 star11)
    (supports instrument6 infrared0)
    (direction__________ star3)
    (calibration_target instrument1 groundstation10)
    (direction__________ groundstation8)
    (direction__________ phenomenon21)
    (supports instrument1 infrared3)
    (calibration_target instrument3 groundstation8)
    (calibration_target instrument3 groundstation1)
    (calibration_target instrument8 star3)
    (direction__________ star13)
    (instrument_________ instrument3)
    (direction__________ star5)
    (on_board instrument0 satellite0)
    (calibration_target instrument2 groundstation10)
    (on_board instrument6 satellite2)
    (direction__________ star15)
    (supports instrument10 image1)
    (supports instrument7 infrared0)
    (power_avail satellite3)
    (direction__________ planet20)
    (calibration_target instrument11 groundstation4)
    (satellite__________ satellite0)
    (satellite__________ satellite2)
    (mode_______________ infrared3)
    (direction__________ phenomenon12)
    (supports instrument11 image1)
    (mode_______________ infrared0)
    (on_board instrument1 satellite0)
    (supports instrument4 infrared3)
    (on_board instrument10 satellite3)
    (instrument_________ instrument2)
    (calibration_target instrument10 star3)
    (supports instrument4 infrared0)
    (supports instrument7 image2)
    (supports instrument7 image1)
    (instrument_________ instrument4)
    (satellite__________ satellite3)
    (on_board instrument8 satellite2)
    (calibration_target instrument11 star7)
    (supports instrument2 image2)
    (supports instrument3 image2)
    (supports instrument8 image1)
    (calibration_target instrument4 groundstation4)
    (calibration_target instrument10 groundstation0)
    (supports instrument3 infrared0)
    (direction__________ groundstation2)
    (direction__________ star7)
    (direction__________ groundstation4)
    (calibration_target instrument1 groundstation8)
    (calibration_target instrument1 groundstation1)
    (on_board instrument7 satellite2)
    (instrument_________ instrument7)
    (calibration_target instrument7 groundstation6)
    (calibration_target instrument8 star7)
    (direction__________ groundstation6)
    (direction__________ planet14)
    (calibration_target instrument6 groundstation4)
    (calibration_target instrument9 groundstation2)
    (supports instrument10 infrared3)
    (supports instrument0 image2)
    (instrument_________ instrument6)
    (calibration_target instrument8 groundstation0)
    (supports instrument0 infrared3)
    (supports instrument9 image2)
    (calibration_target instrument5 star7)
    (instrument_________ instrument5)
    (supports instrument9 infrared0)
    (instrument_________ instrument8)
    (supports instrument1 image2)
    (instrument_________ instrument9)
    (calibration_target instrument10 groundstation1)
    (direction__________ groundstation0)
    (pointing satellite0 groundstation10)
    (calibration_target instrument3 groundstation6)
    (supports instrument1 infrared0)
    (direction__________ phenomenon17)
    (instrument_________ instrument11)
    (supports instrument2 infrared3)
    (calibration_target instrument4 groundstation8)
    (mode_______________ image2)
    (direction__________ star18)
    (supports instrument9 image1)
    (on_board instrument4 satellite1)
    (calibration_target instrument0 star11)
    (power_avail satellite1)
    (supports instrument11 image2)
    (injected-----------0)
  )
  (
    :goal
    (
      and
      (pointing satellite0 star13)
      (pointing satellite2 star7)
      (have_image phenomenon12 image1)
      (have_image star13 infrared3)
      (have_image planet14 infrared0)
      (have_image star15 image2)
      (have_image star16 infrared3)
      (have_image phenomenon17 image1)
      (have_image star18 infrared3)
      (have_image phenomenon19 image2)
      (have_image planet20 infrared0)
      (have_image phenomenon21 image1)
      (injected-----------0)
    )
  )
)