(
  define
  (problem instance-3)
  (:domain satellite)
  (:objects phenomenon14 star10 star12 star2 instrument1 planet15 star0 instrument0 image2 instrument5 satellite1 star6 instrument4 instrument2 planet11 groundstation7 star1 satellite0 satellite2 instrument7 star3 infrared0 groundstation9 planet13 groundstation4 star5 image1 groundstation8 instrument3 instrument6)
  (
    :init
    (on_board instrument1 satellite0)
    (calibration_target instrument3 star2)
    (supports instrument1 image1)
    (instrument_________ instrument2)
    (supports instrument7 image2)
    (calibration_target instrument5 groundstation8)
    (supports instrument7 image1)
    (instrument_________ instrument4)
    (supports instrument2 image1)
    (on_board instrument3 satellite1)
    (supports instrument2 image2)
    (supports instrument3 image2)
    (pointing satellite2 star5)
    (direction__________ planet15)
    (calibration_target instrument7 star0)
    (instrument_________ instrument0)
    (satellite__________ satellite1)
    (direction__________ groundstation7)
    (supports instrument2 infrared0)
    (supports instrument3 infrared0)
    (mode_______________ image1)
    (calibration_target instrument5 star2)
    (direction__________ phenomenon14)
    (calibration_target instrument1 groundstation8)
    (instrument_________ instrument1)
    (supports instrument4 image2)
    (on_board instrument7 satellite2)
    (direction__________ planet11)
    (instrument_________ instrument7)
    (direction__________ groundstation4)
    (direction__________ star10)
    (direction__________ groundstation9)
    (calibration_target instrument0 star3)
    (calibration_target instrument4 groundstation7)
    (supports instrument3 image1)
    (direction__________ star6)
    (supports instrument6 image1)
    (supports instrument0 image2)
    (supports instrument5 infrared0)
    (supports instrument6 image2)
    (direction__________ star0)
    (instrument_________ instrument6)
    (power_avail satellite0)
    (power_avail satellite2)
    (supports instrument6 infrared0)
    (direction__________ star3)
    (pointing satellite1 groundstation9)
    (instrument_________ instrument5)
    (direction__________ star1)
    (direction__________ groundstation8)
    (on_board instrument5 satellite2)
    (instrument_________ instrument3)
    (direction__________ star5)
    (on_board instrument0 satellite0)
    (supports instrument5 image1)
    (direction__________ star12)
    (on_board instrument2 satellite1)
    (calibration_target instrument3 groundstation9)
    (supports instrument1 infrared0)
    (calibration_target instrument6 star1)
    (supports instrument7 infrared0)
    (on_board instrument6 satellite2)
    (supports instrument0 image1)
    (satellite__________ satellite0)
    (satellite__________ satellite2)
    (calibration_target instrument7 star2)
    (direction__________ star2)
    (mode_______________ image2)
    (pointing satellite0 planet15)
    (direction__________ planet13)
    (calibration_target instrument2 star2)
    (on_board instrument4 satellite1)
    (power_avail satellite1)
    (mode_______________ infrared0)
    (injected-----------0)
  )
  (
    :goal
    (
      and
      (pointing satellite0 groundstation8)
      (pointing satellite2 star2)
      (have_image star10 infrared0)
      (have_image planet11 image2)
      (have_image star12 image2)
      (have_image planet13 image2)
      (have_image phenomenon14 infrared0)
      (have_image planet15 image1)
      (injected-----------0)
    )
  )
)