(
  define
  (problem instance-2)
  (:domain satellite)
  (:objects phenomenon14 star10 star12 star2 instrument1 planet15 star0 instrument0 image2 satellite1 star6 planet11 instrument2 groundstation7 star1 satellite0 star3 infrared0 groundstation9 planet13 star16 groundstation4 star5 image1 groundstation8 instrument3)
  (
    :init
    (instrument_________ instrument2)
    (supports instrument1 image1)
    (supports instrument2 image1)
    (on_board instrument3 satellite1)
    (supports instrument2 image2)
    (direction__________ planet15)
    (calibration_target instrument3 star5)
    (instrument_________ instrument0)
    (satellite__________ satellite1)
    (direction__________ groundstation7)
    (supports instrument2 infrared0)
    (mode_______________ image1)
    (pointing satellite1 phenomenon14)
    (direction__________ phenomenon14)
    (calibration_target instrument1 star1)
    (calibration_target instrument2 star0)
    (instrument_________ instrument1)
    (pointing satellite0 star16)
    (direction__________ planet11)
    (direction__________ groundstation4)
    (direction__________ star10)
    (direction__________ groundstation9)
    (calibration_target instrument0 star3)
    (calibration_target instrument2 star1)
    (supports instrument3 image1)
    (direction__________ star6)
    (direction__________ star0)
    (calibration_target instrument1 star3)
    (direction__________ star16)
    (power_avail satellite0)
    (supports instrument0 infrared0)
    (calibration_target instrument3 star0)
    (direction__________ star3)
    (direction__________ star1)
    (on_board instrument1 satellite1)
    (direction__________ groundstation8)
    (calibration_target instrument0 groundstation7)
    (supports instrument1 image2)
    (instrument_________ instrument3)
    (direction__________ star5)
    (on_board instrument0 satellite0)
    (direction__________ star12)
    (on_board instrument2 satellite1)
    (calibration_target instrument3 groundstation9)
    (supports instrument1 infrared0)
    (satellite__________ satellite0)
    (supports instrument0 image1)
    (direction__________ star2)
    (direction__________ planet13)
    (mode_______________ image2)
    (power_avail satellite1)
    (mode_______________ infrared0)
    (injected-----------0)
  )
  (
    :goal
    (
      and
      (pointing satellite0 star6)
      (have_image star10 infrared0)
      (have_image planet11 image2)
      (have_image star12 image2)
      (have_image planet13 image2)
      (have_image phenomenon14 infrared0)
      (have_image planet15 image1)
      (have_image star16 image2)
      (injected-----------0)
    )
  )
)