(
  define
  (problem instance-3)
  (:domain zeno-travel)
  (:objects person11 person4 fl3 person12 city4 fl1 person3 person2 fl6 person10 city0 person8 person5 fl5 person7 person1 city3 plane6 fl0 city5 plane5 person13 person9 person6 city1 plane1 plane4 city2 fl2 plane2 fl4 plane3)
  (
    :init
    (at plane3 city3)
    (at person10 city1)
    (canat______ person8)
    (at person7 city2)
    (at person13 city5)
    (at plane4 city1)
    (fuel-level plane6 fl0)
    (next fl4 fl5)
    (at person5 city5)
    (fuel-level plane2 fl6)
    (person_____ person5)
    (fuel-level plane4 fl1)
    (canat______ person9)
    (at person2 city5)
    (person_____ person8)
    (flevel_____ fl6)
    (at plane2 city2)
    (canat______ person7)
    (flevel_____ fl4)
    (canat______ plane2)
    (at person4 city2)
    (at person8 city3)
    (flevel_____ fl1)
    (person_____ person9)
    (canat______ person11)
    (canat______ person4)
    (flevel_____ fl0)
    (fuel-level plane3 fl4)
    (canat______ person3)
    (flevel_____ fl5)
    (person_____ person7)
    (canat______ person6)
    (canat______ person2)
    (canat______ person10)
    (person_____ person11)
    (person_____ person4)
    (aircraft___ plane1)
    (at person12 city2)
    (person_____ person3)
    (person_____ person6)
    (next fl2 fl3)
    (person_____ person2)
    (flevel_____ fl2)
    (person_____ person10)
    (aircraft___ plane4)
    (flevel_____ fl3)
    (city_______ city5)
    (fuel-level plane1 fl5)
    (fuel-level plane5 fl3)
    (at plane6 city0)
    (city_______ city3)
    (canat______ person1)
    (at person9 city4)
    (canat______ plane5)
    (aircraft___ plane3)
    (next fl1 fl2)
    (aircraft___ plane6)
    (next fl3 fl4)
    (canat______ person13)
    (next fl0 fl1)
    (person_____ person1)
    (aircraft___ plane5)
    (canat______ person12)
    (canat______ plane1)
    (person_____ person13)
    (city_______ city4)
    (person_____ person12)
    (at person1 city3)
    (at plane1 city4)
    (city_______ city0)
    (city_______ city1)
    (aircraft___ plane2)
    (city_______ city2)
    (canat______ plane4)
    (at person6 city2)
    (at plane5 city1)
    (at person3 city1)
    (at person11 city4)
    (next fl5 fl6)
    (canat______ plane3)
    (canat______ plane6)
    (canat______ person5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (at person1 city3)
      (at person2 city4)
      (at person3 city2)
      (at person4 city5)
      (at person6 city2)
      (at person7 city5)
      (at person8 city3)
      (at person9 city3)
      (at person10 city0)
      (at person11 city3)
      (at person12 city2)
      (at person13 city3)
      (injected---0)
    )
  )
)