(
  define
  (problem instance-2)
  (:domain zeno-travel)
  (:objects person4 city5 fl3 city4 fl1 plane5 person3 person9 person6 city1 plane1 person2 plane4 fl6 city2 person10 city0 fl2 person8 plane2 person5 fl5 fl4 plane3 person7 person1 city3 fl0)
  (
    :init
    (at plane3 city3)
    (fuel-level plane5 fl3)
    (fuel-level plane1 fl5)
    (canat______ person8)
    (city_______ city3)
    (at person7 city2)
    (canat______ person1)
    (at plane4 city1)
    (next fl4 fl5)
    (at person6 city4)
    (canat______ plane5)
    (at person1 city0)
    (aircraft___ plane3)
    (next fl1 fl2)
    (fuel-level plane2 fl6)
    (at person3 city5)
    (next fl3 fl4)
    (person_____ person5)
    (fuel-level plane4 fl1)
    (at person5 city3)
    (canat______ person9)
    (at person2 city5)
    (person_____ person8)
    (next fl0 fl1)
    (flevel_____ fl6)
    (aircraft___ plane5)
    (person_____ person1)
    (at plane2 city2)
    (flevel_____ fl4)
    (canat______ person7)
    (canat______ plane2)
    (at person8 city5)
    (flevel_____ fl1)
    (person_____ person9)
    (canat______ plane1)
    (canat______ person4)
    (flevel_____ fl0)
    (city_______ city4)
    (fuel-level plane3 fl4)
    (at person9 city3)
    (canat______ person3)
    (flevel_____ fl5)
    (person_____ person7)
    (canat______ person5)
    (canat______ person6)
    (city_______ city1)
    (city_______ city0)
    (city_______ city2)
    (aircraft___ plane2)
    (canat______ person2)
    (canat______ plane4)
    (at person4 city1)
    (person_____ person4)
    (at person10 city2)
    (aircraft___ plane1)
    (canat______ person10)
    (at plane5 city1)
    (person_____ person3)
    (person_____ person6)
    (next fl5 fl6)
    (next fl2 fl3)
    (person_____ person2)
    (flevel_____ fl2)
    (person_____ person10)
    (canat______ plane3)
    (aircraft___ plane4)
    (flevel_____ fl3)
    (at plane1 city4)
    (city_______ city5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (at person1 city1)
      (at person2 city0)
      (at person3 city3)
      (at person4 city2)
      (at person5 city4)
      (at person6 city2)
      (at person7 city5)
      (at person8 city1)
      (at person9 city0)
      (at person10 city0)
      (injected---0)
    )
  )
)