(
  define
  (problem instance-1)
  (:domain zeno-travel)
  (:objects person4 fl3 fl1 person3 person9 person6 city1 plane1 person2 plane4 fl6 city2 person10 city0 fl2 person8 plane2 person5 fl5 fl4 plane3 person7 person1 fl0)
  (
    :init
    (canat______ person8)
    (canat______ person1)
    (at plane4 city1)
    (next fl4 fl5)
    (at person1 city0)
    (aircraft___ plane3)
    (next fl1 fl2)
    (person_____ person5)
    (at person9 city0)
    (next fl3 fl4)
    (fuel-level plane4 fl1)
    (canat______ person9)
    (person_____ person8)
    (at person6 city1)
    (next fl0 fl1)
    (at plane2 city0)
    (flevel_____ fl6)
    (person_____ person1)
    (at person8 city0)
    (at person7 city1)
    (flevel_____ fl4)
    (canat______ person7)
    (canat______ plane2)
    (fuel-level plane3 fl6)
    (canat______ plane1)
    (flevel_____ fl1)
    (person_____ person9)
    (canat______ person4)
    (fuel-level plane1 fl2)
    (flevel_____ fl0)
    (canat______ person3)
    (flevel_____ fl5)
    (at plane3 city0)
    (person_____ person7)
    (canat______ person6)
    (city_______ city1)
    (city_______ city0)
    (city_______ city2)
    (aircraft___ plane2)
    (canat______ person2)
    (at person10 city0)
    (at person4 city1)
    (person_____ person4)
    (aircraft___ plane1)
    (canat______ plane4)
    (canat______ person10)
    (at plane1 city2)
    (at person3 city0)
    (person_____ person3)
    (fuel-level plane2 fl3)
    (at person5 city0)
    (person_____ person6)
    (next fl5 fl6)
    (next fl2 fl3)
    (person_____ person2)
    (flevel_____ fl2)
    (person_____ person10)
    (at person2 city0)
    (canat______ plane3)
    (aircraft___ plane4)
    (flevel_____ fl3)
    (canat______ person5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (at person1 city0)
      (at person2 city0)
      (at person3 city0)
      (at person4 city1)
      (at person5 city1)
      (at person6 city1)
      (at person7 city2)
      (at person8 city1)
      (at person9 city1)
      (at person10 city0)
      (injected---0)
    )
  )
)