(
  define
  (problem instance-5)
  (:domain zeno-travel)
  (:objects person11 person4 fl3 person12 fl1 person3 person17 person16 person2 fl6 person10 person20 city0 person8 person5 person18 fl5 person15 person7 person1 plane6 fl0 plane5 person13 person9 person6 city1 plane1 plane4 person19 city2 fl2 plane2 fl4 plane3 person14)
  (
    :init
    (at person10 city1)
    (person_____ person17)
    (at person19 city0)
    (canat______ person8)
    (at person12 city1)
    (at plane4 city1)
    (at person14 city0)
    (next fl4 fl5)
    (person_____ person5)
    (at person9 city2)
    (fuel-level plane4 fl1)
    (canat______ person9)
    (canat______ person14)
    (person_____ person8)
    (flevel_____ fl6)
    (at person18 city2)
    (at person7 city0)
    (at person8 city1)
    (canat______ person7)
    (flevel_____ fl4)
    (canat______ plane2)
    (at person15 city2)
    (flevel_____ fl1)
    (person_____ person9)
    (person_____ person14)
    (canat______ person11)
    (canat______ person4)
    (flevel_____ fl0)
    (canat______ person3)
    (flevel_____ fl5)
    (person_____ person7)
    (canat______ person6)
    (canat______ person2)
    (canat______ person19)
    (canat______ person10)
    (person_____ person11)
    (at person13 city2)
    (person_____ person4)
    (aircraft___ plane1)
    (at plane5 city0)
    (fuel-level plane5 fl4)
    (at plane1 city2)
    (person_____ person3)
    (fuel-level plane2 fl3)
    (canat______ person18)
    (person_____ person6)
    (next fl2 fl3)
    (person_____ person2)
    (person_____ person19)
    (person_____ person10)
    (flevel_____ fl2)
    (at person2 city1)
    (aircraft___ plane4)
    (flevel_____ fl3)
    (at person20 city0)
    (person_____ person18)
    (canat______ person1)
    (at person5 city1)
    (canat______ person20)
    (canat______ plane5)
    (aircraft___ plane3)
    (next fl1 fl2)
    (canat______ person16)
    (aircraft___ plane6)
    (at person17 city2)
    (next fl3 fl4)
    (at person11 city1)
    (canat______ person13)
    (at plane6 city1)
    (next fl0 fl1)
    (at plane2 city0)
    (person_____ person1)
    (aircraft___ plane5)
    (canat______ person12)
    (person_____ person20)
    (person_____ person16)
    (fuel-level plane3 fl6)
    (at person1 city1)
    (canat______ plane1)
    (person_____ person13)
    (fuel-level plane1 fl2)
    (person_____ person12)
    (canat______ person15)
    (at plane3 city0)
    (city_______ city0)
    (city_______ city1)
    (aircraft___ plane2)
    (city_______ city2)
    (canat______ plane4)
    (at person4 city1)
    (at person6 city2)
    (at person16 city1)
    (fuel-level plane6 fl4)
    (at person3 city0)
    (canat______ person17)
    (person_____ person15)
    (next fl5 fl6)
    (canat______ plane3)
    (canat______ plane6)
    (canat______ person5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (at person1 city0)
      (at person3 city2)
      (at person4 city0)
      (at person5 city1)
      (at person6 city2)
      (at person7 city1)
      (at person8 city2)
      (at person10 city1)
      (at person11 city2)
      (at person12 city1)
      (at person13 city1)
      (at person14 city0)
      (at person15 city1)
      (at person16 city1)
      (at person17 city1)
      (at person18 city2)
      (at person19 city2)
      (at person20 city0)
      (injected---0)
    )
  )
)