(
  define
  (problem instance-1)
  (:domain depots)
  (:objects truck0 pallet0 distributor0 hoist2 pallet1 depot0 truck1 hoist1 crate0 hoist0 crate1 pallet2 distributor1)
  (
    :init
    (crate_____ crate0)
    (on crate0 pallet2)
    (available hoist2)
    (available hoist1)
    (surface___ pallet2)
    (pallet____ pallet2)
    (hoist_____ hoist2)
    (at pallet1 distributor0)
    (hoist_____ hoist1)
    (surface___ crate1)
    (at pallet2 distributor1)
    (at crate1 distributor1)
    (place_____ depot0)
    (distributor distributor0)
    (at truck1 depot0)
    (locatable_ pallet2)
    (place_____ distributor0)
    (locatable_ crate1)
    (at hoist2 distributor1)
    (clear crate1)
    (pallet____ pallet0)
    (surface___ pallet1)
    (pallet____ pallet1)
    (at truck0 distributor1)
    (surface___ pallet0)
    (locatable_ hoist0)
    (surface___ crate0)
    (locatable_ pallet0)
    (locatable_ pallet1)
    (available hoist0)
    (crate_____ crate1)
    (locatable_ crate0)
    (clear pallet0)
    (place_____ distributor1)
    (clear pallet1)
    (distributor distributor1)
    (hoist_____ hoist0)
    (on crate1 crate0)
    (at hoist1 distributor0)
    (at hoist0 depot0)
    (locatable_ truck0)
    (locatable_ truck1)
    (truck_____ truck1)
    (depot_____ depot0)
    (truck_____ truck0)
    (at pallet0 depot0)
    (locatable_ hoist2)
    (locatable_ hoist1)
    (at crate0 distributor1)
    (injected---0)
  )
  (
    :goal
    (
      and
      (on crate0 crate1)
      (on crate1 pallet2)
      (injected---0)
    )
  )
)