(
  define
  (problem instance-4)
  (:domain depots)
  (:objects hoist5 truck4 distributor2 pallet0 distributor0 crate3 pallet1 crate2 crate0 pallet5 truck3 pallet6 truck2 depot1 distributor4 hoist6 depot0 truck1 hoist1 depot2 hoist4 distributor3 pallet7 distributor1 truck0 hoist2 pallet4 crate4 pallet3 hoist3 hoist7 crate1 pallet2 hoist0)
  (
    :init
    (crate_____ crate0)
    (at hoist5 distributor2)
    (depot_____ depot2)
    (pallet____ pallet3)
    (at hoist2 depot2)
    (available hoist1)
    (locatable_ truck2)
    (available hoist6)
    (pallet____ pallet4)
    (pallet____ pallet6)
    (clear pallet4)
    (surface___ crate2)
    (at pallet1 depot1)
    (at hoist4 distributor1)
    (pallet____ pallet2)
    (hoist_____ hoist2)
    (surface___ pallet6)
    (surface___ crate1)
    (locatable_ pallet3)
    (at hoist7 distributor4)
    (truck_____ truck4)
    (place_____ depot0)
    (distributor distributor0)
    (locatable_ pallet6)
    (locatable_ pallet2)
    (on crate1 pallet2)
    (place_____ distributor0)
    (clear crate2)
    (place_____ depot2)
    (pallet____ pallet0)
    (crate_____ crate3)
    (pallet____ pallet1)
    (at pallet3 distributor0)
    (surface___ pallet0)
    (available hoist7)
    (on crate2 pallet6)
    (surface___ crate0)
    (locatable_ pallet0)
    (at truck0 distributor4)
    (at pallet7 distributor4)
    (locatable_ pallet1)
    (place_____ depot1)
    (available hoist0)
    (at truck1 distributor0)
    (at pallet5 distributor2)
    (at hoist6 distributor3)
    (locatable_ crate0)
    (clear pallet0)
    (distributor distributor1)
    (clear pallet1)
    (at hoist1 depot1)
    (clear crate0)
    (at crate3 distributor2)
    (at hoist0 depot0)
    (available hoist4)
    (surface___ pallet7)
    (locatable_ truck0)
    (at crate0 distributor0)
    (locatable_ hoist3)
    (distributor distributor2)
    (at crate1 depot2)
    (truck_____ truck3)
    (truck_____ truck1)
    (locatable_ truck1)
    (distributor distributor3)
    (locatable_ pallet5)
    (locatable_ crate4)
    (at crate4 distributor4)
    (locatable_ hoist1)
    (locatable_ hoist6)
    (on crate3 pallet5)
    (surface___ crate3)
    (at pallet6 distributor3)
    (on crate0 pallet3)
    (available hoist3)
    (clear crate4)
    (surface___ pallet3)
    (available hoist2)
    (locatable_ crate3)
    (locatable_ pallet4)
    (hoist_____ hoist3)
    (surface___ pallet2)
    (at truck4 depot2)
    (locatable_ truck4)
    (truck_____ truck2)
    (depot_____ depot1)
    (clear crate3)
    (hoist_____ hoist1)
    (at crate2 distributor3)
    (hoist_____ hoist6)
    (crate_____ crate4)
    (locatable_ crate2)
    (on crate4 pallet7)
    (locatable_ crate1)
    (at pallet4 distributor1)
    (at truck3 depot2)
    (at truck2 distributor0)
    (locatable_ hoist7)
    (clear crate1)
    (surface___ pallet1)
    (distributor distributor4)
    (locatable_ hoist0)
    (place_____ distributor4)
    (crate_____ crate2)
    (hoist_____ hoist7)
    (crate_____ crate1)
    (locatable_ hoist4)
    (place_____ distributor1)
    (pallet____ pallet5)
    (hoist_____ hoist0)
    (pallet____ pallet7)
    (locatable_ hoist5)
    (surface___ pallet5)
    (surface___ crate4)
    (locatable_ truck3)
    (at hoist3 distributor0)
    (place_____ distributor2)
    (hoist_____ hoist4)
    (place_____ distributor3)
    (depot_____ depot0)
    (locatable_ pallet7)
    (truck_____ truck0)
    (at pallet2 depot2)
    (at pallet0 depot0)
    (available hoist5)
    (locatable_ hoist2)
    (surface___ pallet4)
    (hoist_____ hoist5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (on crate0 pallet7)
      (on crate1 pallet3)
      (on crate2 crate4)
      (on crate4 pallet4)
      (injected---0)
    )
  )
)