(
  define
  (problem instance-5)
  (:domain depots)
  (:objects truck5 hoist8 hoist5 truck4 distributor2 pallet0 distributor0 crate3 pallet1 pallet8 crate2 crate0 pallet5 truck3 pallet6 truck2 depot1 distributor4 hoist6 depot0 truck1 hoist1 depot2 crate6 hoist4 distributor3 pallet7 distributor1 depot3 truck0 crate5 hoist2 pallet4 crate4 pallet3 hoist3 hoist7 crate1 pallet2 hoist0)
  (
    :init
    (clear pallet7)
    (at crate6 distributor2)
    (crate_____ crate0)
    (depot_____ depot2)
    (pallet____ pallet8)
    (at hoist2 depot2)
    (pallet____ pallet3)
    (available hoist1)
    (locatable_ truck2)
    (available hoist6)
    (pallet____ pallet6)
    (clear pallet4)
    (at hoist5 distributor1)
    (at pallet1 depot1)
    (hoist_____ hoist8)
    (surface___ crate2)
    (hoist_____ hoist2)
    (surface___ pallet6)
    (surface___ crate1)
    (pallet____ pallet2)
    (locatable_ pallet8)
    (truck_____ truck4)
    (crate_____ crate5)
    (locatable_ pallet3)
    (place_____ depot0)
    (distributor distributor0)
    (locatable_ pallet6)
    (locatable_ pallet2)
    (at hoist8 distributor4)
    (crate_____ crate6)
    (at truck4 distributor4)
    (clear crate2)
    (place_____ distributor0)
    (at hoist6 distributor2)
    (place_____ depot2)
    (at hoist3 depot3)
    (on crate6 crate0)
    (pallet____ pallet0)
    (crate_____ crate3)
    (pallet____ pallet1)
    (at pallet8 distributor4)
    (surface___ pallet0)
    (depot_____ depot3)
    (available hoist7)
    (surface___ crate0)
    (locatable_ pallet0)
    (place_____ depot1)
    (at hoist7 distributor3)
    (at crate5 depot1)
    (locatable_ pallet1)
    (available hoist0)
    (locatable_ crate0)
    (distributor distributor1)
    (at pallet6 distributor2)
    (truck_____ truck5)
    (at hoist1 depot1)
    (surface___ crate5)
    (at truck1 distributor1)
    (at pallet5 distributor1)
    (at hoist0 depot0)
    (available hoist4)
    (on crate0 pallet6)
    (surface___ pallet7)
    (place_____ depot3)
    (surface___ crate6)
    (locatable_ truck0)
    (at crate3 distributor1)
    (distributor distributor2)
    (truck_____ truck3)
    (at truck3 distributor2)
    (truck_____ truck1)
    (locatable_ truck1)
    (distributor distributor3)
    (locatable_ hoist3)
    (locatable_ pallet5)
    (at pallet4 distributor0)
    (locatable_ crate4)
    (at crate4 distributor4)
    (locatable_ hoist1)
    (at pallet7 distributor3)
    (on crate3 pallet5)
    (surface___ crate3)
    (locatable_ hoist6)
    (at pallet3 depot3)
    (available hoist3)
    (clear crate6)
    (clear crate4)
    (available hoist2)
    (available hoist8)
    (locatable_ crate3)
    (surface___ pallet8)
    (locatable_ pallet4)
    (surface___ pallet3)
    (hoist_____ hoist3)
    (surface___ pallet2)
    (locatable_ truck4)
    (truck_____ truck2)
    (at crate0 distributor2)
    (on crate2 pallet0)
    (clear crate3)
    (depot_____ depot1)
    (hoist_____ hoist6)
    (hoist_____ hoist1)
    (clear pallet3)
    (crate_____ crate4)
    (at crate2 depot0)
    (locatable_ crate2)
    (clear pallet2)
    (locatable_ crate1)
    (on crate1 pallet1)
    (at crate1 depot1)
    (locatable_ hoist7)
    (at truck5 depot3)
    (surface___ pallet1)
    (distributor distributor4)
    (locatable_ hoist0)
    (place_____ distributor4)
    (crate_____ crate2)
    (locatable_ hoist2)
    (on crate4 pallet8)
    (locatable_ crate6)
    (hoist_____ hoist7)
    (on crate5 crate1)
    (crate_____ crate1)
    (at truck2 distributor4)
    (locatable_ truck5)
    (at truck0 distributor2)
    (locatable_ hoist4)
    (place_____ distributor1)
    (at hoist4 distributor0)
    (pallet____ pallet5)
    (hoist_____ hoist0)
    (pallet____ pallet7)
    (locatable_ hoist5)
    (surface___ pallet5)
    (surface___ crate4)
    (locatable_ truck3)
    (place_____ distributor2)
    (place_____ distributor3)
    (hoist_____ hoist4)
    (pallet____ pallet4)
    (depot_____ depot0)
    (locatable_ pallet7)
    (truck_____ truck0)
    (at pallet2 depot2)
    (at pallet0 depot0)
    (available hoist5)
    (locatable_ hoist8)
    (locatable_ crate5)
    (surface___ pallet4)
    (hoist_____ hoist5)
    (clear crate5)
    (injected---0)
  )
  (
    :goal
    (
      and
      (on crate0 pallet8)
      (on crate1 pallet7)
      (on crate2 pallet5)
      (on crate3 pallet2)
      (on crate4 crate3)
      (on crate5 pallet3)
      (on crate6 pallet6)
      (injected---0)
    )
  )
)