(
  define
  (problem instance-2)
  (:domain depots)
  (:objects truck2 depot1 depot0 truck1 hoist1 hoist4 distributor2 distributor1 pallet0 truck0 distributor0 hoist2 pallet4 pallet1 crate2 crate0 pallet3 truck3 hoist3 crate1 pallet2 hoist0)
  (
    :init
    (crate_____ crate0)
    (pallet____ pallet3)
    (available hoist1)
    (locatable_ truck2)
    (pallet____ pallet2)
    (surface___ crate2)
    (at pallet1 depot1)
    (at pallet2 distributor0)
    (hoist_____ hoist2)
    (surface___ crate1)
    (at pallet4 distributor2)
    (locatable_ pallet3)
    (place_____ depot0)
    (distributor distributor0)
    (locatable_ pallet2)
    (place_____ distributor0)
    (clear crate2)
    (pallet____ pallet0)
    (at crate1 distributor2)
    (pallet____ pallet1)
    (surface___ pallet0)
    (surface___ crate0)
    (place_____ depot1)
    (locatable_ pallet0)
    (locatable_ pallet1)
    (available hoist0)
    (locatable_ crate0)
    (at truck2 depot1)
    (distributor distributor1)
    (clear pallet1)
    (at hoist1 depot1)
    (clear crate0)
    (at truck1 distributor1)
    (at hoist0 depot0)
    (available hoist4)
    (on crate1 pallet4)
    (locatable_ truck0)
    (locatable_ hoist3)
    (locatable_ truck1)
    (truck_____ truck3)
    (truck_____ truck1)
    (at truck3 depot1)
    (distributor distributor2)
    (at hoist2 distributor0)
    (locatable_ hoist1)
    (at crate0 distributor1)
    (at hoist4 distributor2)
    (on crate0 pallet3)
    (surface___ pallet3)
    (available hoist2)
    (locatable_ pallet4)
    (hoist_____ hoist3)
    (surface___ pallet2)
    (truck_____ truck2)
    (on crate2 pallet0)
    (depot_____ depot1)
    (hoist_____ hoist1)
    (at crate2 depot0)
    (locatable_ crate2)
    (clear pallet2)
    (locatable_ crate1)
    (clear crate1)
    (surface___ pallet1)
    (at truck0 distributor1)
    (locatable_ hoist0)
    (crate_____ crate2)
    (crate_____ crate1)
    (locatable_ hoist4)
    (place_____ distributor1)
    (hoist_____ hoist0)
    (locatable_ truck3)
    (place_____ distributor2)
    (pallet____ pallet4)
    (hoist_____ hoist4)
    (at pallet3 distributor1)
    (depot_____ depot0)
    (truck_____ truck0)
    (at pallet0 depot0)
    (surface___ pallet4)
    (locatable_ hoist2)
    (available hoist3)
    (at hoist3 distributor1)
    (injected---0)
  )
  (
    :goal
    (
      and
      (on crate0 pallet2)
      (on crate1 crate2)
      (on crate2 pallet1)
      (injected---0)
    )
  )
)