(
  define
  (problem instance-1)
  (:domain rover)
  (:objects waypoint0 rover0 rover1store colour rover1 low_res waypoint1 general rover2 waypoint3 objective1 camera1 camera2 objective0 camera0 rover2store waypoint2 waypoint4 rover0store high_res)
  (
    :init
    (can_traverse rover0 waypoint0 waypoint1)
    (visible waypoint0 waypoint1)
    (can_traverse rover2 waypoint2 waypoint0)
    (can_traverse rover1 waypoint1 waypoint0)
    (available rover0)
    (visible waypoint0 waypoint3)
    (can_traverse rover1 waypoint3 waypoint0)
    (can_traverse rover2 waypoint4 waypoint3)
    (on_board camera2 rover1)
    (visible waypoint2 waypoint3)
    (camera_____________________ camera1)
    (can_traverse rover0 waypoint0 waypoint4)
    (visible waypoint0 waypoint4)
    (on_board camera0 rover1)
    (can_traverse rover2 waypoint3 waypoint4)
    (at_rock_sample waypoint0)
    (rover______________________ rover0)
    (camera_____________________ camera2)
    (visible waypoint2 waypoint4)
    (supports camera2 colour)
    (visible waypoint4 waypoint0)
    (mode_______________________ colour)
    (supports camera2 high_res)
    (mode_______________________ high_res)
    (rover______________________ rover1)
    (can_traverse rover0 waypoint4 waypoint0)
    (empty rover1store)
    (equipped_for_imaging rover2)
    (empty rover0store)
    (calibration_target camera0 objective0)
    (visible_from objective1 waypoint3)
    (visible waypoint0 waypoint2)
    (at_soil_sample waypoint0)
    (waypoint___________________ waypoint0)
    (can_traverse rover1 waypoint0 waypoint3)
    (at_rock_sample waypoint2)
    (visible waypoint1 waypoint3)
    (can_traverse rover0 waypoint1 waypoint3)
    (rover______________________ rover2)
    (at_soil_sample waypoint3)
    (waypoint___________________ waypoint3)
    (camera_____________________ camera0)
    (visible_from objective1 waypoint4)
    (visible waypoint3 waypoint2)
    (visible waypoint3 waypoint1)
    (can_traverse rover0 waypoint2 waypoint0)
    (visible waypoint2 waypoint0)
    (visible waypoint1 waypoint4)
    (can_traverse rover0 waypoint3 waypoint1)
    (visible waypoint4 waypoint3)
    (supports camera2 low_res)
    (visible_from objective1 waypoint2)
    (waypoint___________________ waypoint4)
    (at rover2 waypoint2)
    (can_traverse rover1 waypoint0 waypoint1)
    (store______________________ rover0store)
    (supports camera1 colour)
    (visible waypoint3 waypoint4)
    (objective__________________ objective0)
    (waypoint___________________ waypoint2)
    (waypoint___________________ waypoint1)
    (at_lander general waypoint3)
    (can_traverse rover0 waypoint0 waypoint2)
    (objective__________________ objective1)
    (equipped_for_soil_analysis rover0)
    (equipped_for_imaging rover1)
    (available rover1)
    (visible waypoint1 waypoint0)
    (can_traverse rover0 waypoint1 waypoint0)
    (empty rover2store)
    (store_of rover2store rover2)
    (visible_from objective0 waypoint2)
    (visible waypoint3 waypoint0)
    (can_traverse rover2 waypoint0 waypoint2)
    (can_traverse rover2 waypoint0 waypoint1)
    (visible_from objective0 waypoint3)
    (available rover2)
    (at_rock_sample waypoint3)
    (supports camera0 high_res)
    (equipped_for_soil_analysis rover2)
    (can_traverse rover2 waypoint2 waypoint3)
    (store_of rover1store rover1)
    (can_traverse rover2 waypoint1 waypoint0)
    (calibration_target camera2 objective1)
    (store______________________ rover2store)
    (at_rock_sample waypoint1)
    (on_board camera1 rover2)
    (visible waypoint4 waypoint2)
    (visible waypoint4 waypoint1)
    (at rover0 waypoint1)
    (at rover1 waypoint0)
    (store_of rover0store rover0)
    (channel_free general)
    (store______________________ rover1store)
    (mode_______________________ low_res)
    (visible_from objective0 waypoint0)
    (calibration_target camera1 objective1)
    (lander_____________________ general)
    (can_traverse rover2 waypoint3 waypoint2)
    (injected-------------------0)
  )
  (
    :goal
    (
      and
      (communicated_soil_data waypoint3)
      (communicated_soil_data waypoint0)
      (communicated_image_data objective0 high_res)
      (communicated_image_data objective0 colour)
      (communicated_image_data objective1 colour)
      (injected-------------------0)
    )
  )
)