(
  define
  (problem instance-3)
  (:domain gripper-strips)
  (:objects lgripper3 lgripper1 ball1 ball7 rgripper3 robot4 rgripper1 room3 ball3 robot1 ball2 rgripper4 ball10 robot6 robot3 room2 lgripper5 room6 room4 ball5 lgripper4 room1 ball9 rgripper2 robot5 rgripper5 ball8 robot2 ball4 lgripper2 lgripper6 rgripper6 ball6 room5)
  (
    :init
    (at-robby robot2 room3)
    (free robot3 lgripper3)
    (gripper__ lgripper1)
    (at-robby robot3 room3)
    (at ball4 room5)
    (stuff____ ball4)
    (at ball6 room2)
    (robot____ robot6)
    (at-robby robot5 room4)
    (at ball3 room3)
    (stuff____ ball10)
    (at ball10 room2)
    (room_____ room1)
    (at ball8 room5)
    (robot____ robot2)
    (gripper__ lgripper5)
    (at ball5 room4)
    (robot____ robot4)
    (at ball7 room1)
    (stuff____ ball2)
    (gripper__ lgripper2)
    (free robot4 lgripper4)
    (stuff____ ball7)
    (gripper__ rgripper5)
    (stuff____ ball3)
    (stuff____ ball1)
    (robot____ robot5)
    (free robot2 rgripper2)
    (gripper__ rgripper4)
    (robot____ robot1)
    (free robot5 lgripper5)
    (room_____ room3)
    (free robot2 lgripper2)
    (at ball2 room5)
    (at-robby robot4 room5)
    (room_____ room4)
    (robot____ robot3)
    (at-robby robot1 room4)
    (free robot6 rgripper6)
    (room_____ room2)
    (stuff____ ball8)
    (gripper__ rgripper6)
    (gripper__ rgripper3)
    (gripper__ lgripper3)
    (at-robby robot6 room3)
    (room_____ room6)
    (free robot6 lgripper6)
    (free robot1 lgripper1)
    (free robot1 rgripper1)
    (stuff____ ball6)
    (room_____ room5)
    (gripper__ lgripper4)
    (at ball1 room6)
    (at ball9 room2)
    (gripper__ rgripper2)
    (gripper__ lgripper6)
    (free robot4 rgripper4)
    (stuff____ ball5)
    (free robot5 rgripper5)
    (free robot3 rgripper3)
    (gripper__ rgripper1)
    (stuff____ ball9)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at ball1 room6)
      (at ball2 room6)
      (at ball3 room3)
      (at ball4 room5)
      (at ball5 room5)
      (at ball6 room4)
      (at ball7 room6)
      (at ball8 room6)
      (at ball9 room3)
      (at ball10 room1)
      (injected-0)
    )
  )
)