(
  define
  (problem instance-4)
  (:domain gripper-strips)
  (:objects lgripper3 ball12 lgripper1 room8 ball1 ball7 rgripper3 robot4 rgripper7 rgripper1 room3 ball3 robot1 ball2 rgripper4 lgripper7 ball10 robot6 robot3 room2 lgripper5 room6 room4 ball5 lgripper4 room1 ball9 ball11 room7 rgripper2 robot5 rgripper5 ball8 robot2 ball4 robot7 lgripper2 lgripper6 rgripper6 ball6 room5)
  (
    :init
    (free robot3 lgripper3)
    (stuff____ ball11)
    (gripper__ lgripper1)
    (at-robby robot7 room1)
    (stuff____ ball4)
    (at ball12 room4)
    (at ball8 room2)
    (robot____ robot6)
    (stuff____ ball10)
    (at-robby robot5 room2)
    (at ball5 room3)
    (at ball3 room4)
    (at-robby robot6 room6)
    (at ball7 room3)
    (gripper__ lgripper5)
    (room_____ room1)
    (robot____ robot2)
    (robot____ robot4)
    (stuff____ ball2)
    (at ball2 room4)
    (gripper__ lgripper2)
    (free robot4 lgripper4)
    (stuff____ ball7)
    (gripper__ rgripper7)
    (stuff____ ball3)
    (gripper__ lgripper7)
    (gripper__ rgripper5)
    (stuff____ ball1)
    (robot____ robot5)
    (free robot2 rgripper2)
    (gripper__ rgripper4)
    (room_____ room8)
    (robot____ robot1)
    (at ball6 room6)
    (free robot5 lgripper5)
    (at-robby robot2 room6)
    (free robot2 lgripper2)
    (at-robby robot3 room7)
    (free robot7 rgripper7)
    (free robot7 lgripper7)
    (at ball1 room5)
    (at ball11 room7)
    (room_____ room3)
    (free robot6 rgripper6)
    (robot____ robot3)
    (room_____ room4)
    (room_____ room2)
    (stuff____ ball12)
    (stuff____ ball8)
    (gripper__ rgripper6)
    (gripper__ rgripper3)
    (at-robby robot1 room2)
    (gripper__ lgripper3)
    (room_____ room6)
    (free robot6 lgripper6)
    (free robot1 lgripper1)
    (free robot1 rgripper1)
    (at-robby robot4 room7)
    (stuff____ ball6)
    (room_____ room5)
    (robot____ robot7)
    (at ball10 room7)
    (gripper__ lgripper4)
    (at ball9 room2)
    (gripper__ rgripper2)
    (gripper__ lgripper6)
    (free robot4 rgripper4)
    (at ball4 room2)
    (stuff____ ball5)
    (room_____ room7)
    (free robot5 rgripper5)
    (free robot3 rgripper3)
    (gripper__ rgripper1)
    (stuff____ ball9)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at ball1 room3)
      (at ball2 room2)
      (at ball3 room1)
      (at ball4 room1)
      (at ball5 room2)
      (at ball6 room7)
      (at ball7 room7)
      (at ball8 room4)
      (at ball9 room5)
      (at ball10 room5)
      (at ball11 room5)
      (at ball12 room7)
      (injected-0)
    )
  )
)