(
  define
  (problem instance-2)
  (:domain gripper-strips)
  (:objects lgripper3 robot3 room2 lgripper1 lgripper5 ball5 lgripper4 room1 ball1 ball7 rgripper3 robot4 rgripper2 rgripper1 room3 robot5 rgripper5 ball8 robot2 ball4 lgripper2 ball3 robot1 ball6 ball2 rgripper4)
  (
    :init
    (at-robby robot2 room3)
    (free robot3 lgripper3)
    (gripper__ lgripper1)
    (at-robby robot3 room3)
    (stuff____ ball4)
    (at-robby robot5 room3)
    (at ball7 room2)
    (at-robby robot4 room2)
    (at ball8 room2)
    (at ball5 room3)
    (room_____ room1)
    (robot____ robot2)
    (gripper__ lgripper5)
    (robot____ robot4)
    (stuff____ ball2)
    (gripper__ lgripper2)
    (at ball1 room1)
    (free robot4 lgripper4)
    (at ball3 room2)
    (stuff____ ball7)
    (gripper__ rgripper5)
    (stuff____ ball3)
    (stuff____ ball1)
    (robot____ robot5)
    (free robot2 rgripper2)
    (gripper__ rgripper4)
    (robot____ robot1)
    (free robot5 lgripper5)
    (room_____ room3)
    (free robot2 lgripper2)
    (robot____ robot3)
    (room_____ room2)
    (stuff____ ball8)
    (gripper__ rgripper3)
    (at-robby robot1 room2)
    (gripper__ lgripper3)
    (free robot1 lgripper1)
    (free robot1 rgripper1)
    (stuff____ ball6)
    (at ball4 room3)
    (gripper__ lgripper4)
    (gripper__ rgripper2)
    (free robot4 rgripper4)
    (stuff____ ball5)
    (at ball2 room1)
    (at ball6 room3)
    (free robot5 rgripper5)
    (free robot3 rgripper3)
    (gripper__ rgripper1)
    (injected-0)
  )
  (
    :goal
    (
      and
      (at ball1 room3)
      (at ball2 room1)
      (at ball3 room2)
      (at ball4 room3)
      (at ball5 room1)
      (at ball6 room2)
      (at ball7 room2)
      (at ball8 room2)
      (injected-0)
    )
  )
)