(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	image1 - mode
	infrared3 - mode
	infrared0 - mode
	image2 - mode
	Star5 - direction
	GroundStation9 - direction
	GroundStation10 - direction
	Star11 - direction
	GroundStation8 - direction
	GroundStation6 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	GroundStation0 - direction
	GroundStation4 - direction
	Star7 - direction
	Star3 - direction
	Phenomenon12 - direction
	Star13 - direction
	Planet14 - direction
	Star15 - direction
	Star16 - direction
	Phenomenon17 - direction
	Star18 - direction
	Phenomenon19 - direction
	Planet20 - direction
	Phenomenon21 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 infrared3)
	(calibration_target instrument0 Star11)
	(supports instrument1 image2)
	(supports instrument1 infrared3)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation10)
	(calibration_target instrument1 GroundStation8)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 infrared3)
	(supports instrument2 image2)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 GroundStation10)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation10)
	(supports instrument3 infrared0)
	(supports instrument3 image2)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star11)
	(supports instrument4 infrared0)
	(supports instrument4 infrared3)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation8)
	(supports instrument5 image2)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star7)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation8)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 infrared0)
	(supports instrument7 image2)
	(supports instrument7 image1)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 Star3)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star5)
	(supports instrument9 image2)
	(supports instrument9 infrared0)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 image2)
	(supports instrument10 infrared3)
	(supports instrument10 image1)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 image2)
	(supports instrument11 image1)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation4)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet20)
)
(:goal (and
	(pointing satellite0 Star13)
	(pointing satellite2 Star7)
	(have_image Phenomenon12 image1)
	(have_image Star13 infrared3)
	(have_image Planet14 infrared0)
	(have_image Star15 image2)
	(have_image Star16 infrared3)
	(have_image Phenomenon17 image1)
	(have_image Star18 infrared3)
	(have_image Phenomenon19 image2)
	(have_image Planet20 infrared0)
	(have_image Phenomenon21 image1)
))

)
